name: Secure Pipeline

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Weekly scan on Sundays

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Bandit (SAST)
      run: |
        pip install bandit
        bandit -r .

    - name: Check dependencies
      run: |
        pip install safety
        safety check --full-report

    - name: Check for secrets
      run: |
        pip install trufflehog
        trufflehog filesystem --directory .
